"""Shared data models for the Guardian pipeline."""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum

from pydantic import BaseModel, Field


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Severity(str, Enum):
    DEBUG = "DEBUG"
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class Document(BaseModel):
    """A document ingested into the pipeline."""

    doc_id: str
    content: str
    source_path: str = ""
    metadata: dict = Field(default_factory=dict)
    ingested_at: datetime = Field(default_factory=_utcnow)


class EmbeddingRecord(BaseModel):
    """An embedding vector associated with a document."""

    doc_id: str
    embedding: list[float]
    model_name: str
    created_at: datetime = Field(default_factory=_utcnow)


class DriftResult(BaseModel):
    """Result of a drift detection test."""

    test_name: str
    statistic: float
    p_value: float | None = None
    threshold: float
    is_drifted: bool
    details: dict = Field(default_factory=dict)
    measured_at: datetime = Field(default_factory=_utcnow)


class HallucinationRisk(BaseModel):
    """A detected hallucination-triggering pattern."""

    risk_type: str
    severity: Severity
    doc_ids: list[str]
    description: str
    confidence: float = Field(ge=0.0, le=1.0)
    detected_at: datetime = Field(default_factory=_utcnow)


class QualityCheckResult(BaseModel):
    """Result from a data quality check."""

    check_name: str
    dataset: str
    passed: bool
    metric_value: float | None = None
    details: dict = Field(default_factory=dict)
    checked_at: datetime = Field(default_factory=_utcnow)


class RAGQualityResult(BaseModel):
    """RAG pipeline quality metrics."""

    metric_name: str
    score: float
    details: dict = Field(default_factory=dict)
    measured_at: datetime = Field(default_factory=_utcnow)


class Alert(BaseModel):
    """An alert generated by the pipeline."""

    severity: Severity
    source_module: str
    title: str
    message: str
    context: dict = Field(default_factory=dict)
    created_at: datetime = Field(default_factory=_utcnow)


class PipelineRunResult(BaseModel):
    """Complete result of a single pipeline execution."""

    run_id: str
    started_at: datetime
    completed_at: datetime | None = None
    documents_processed: int = 0
    drift_results: list[DriftResult] = Field(default_factory=list)
    hallucination_risks: list[HallucinationRisk] = Field(default_factory=list)
    quality_results: list[QualityCheckResult] = Field(default_factory=list)
    rag_results: list[RAGQualityResult] = Field(default_factory=list)
    alerts: list[Alert] = Field(default_factory=list)
